package com.thirdgallon.namegenerator.generator

object Surnames {

    private val _COMMON = arrayOf(
        "Allen",
        "Arnold",
        "Batts",
        "Bennett",
        "Clark",
        "Cooper",
        "Cruz",
        "Farmer",
        "Flores",
        "Fox",
        "Green",
        "Hall",
        "Harris",
        "Hart",
        "Hill",
        "Howard",
        "Jones",
        "Junk",
        "Knight",
        "Lee",
        "Lewis",
        "Long",
        "Morris",
        "Reed",
        "Rigg",
        "Robin",
        "Schmidt",
        "Small",
        "Smith",
        "Stewart",
        "Stone",
        "Taylor",
        "Young",
    )

    val COMPLETE = _COMMON + arrayOf(
        "Anderson",
        "Barton",
        "Brown",
        "Davis",
        "Garcia",
        "Jackson",
        "Jenkins",
        "Johnson",
        "Martin",
        "Miller",
        "Thompson",
        "Tomlinson",
        "Washington",
        "Williams",
    )

    val ROOT = _COMMON + arrayOf(
        "Adam",
        "Alex",
        "Barf",
        "Bart",
        "Bat",
        "Big",
        "Butt",
        "Chuckle",
        "City",
        "Face",
        "Jenk",
        "John",
        "Man",
        "Mart",
        "Mill",
        "Mitch",
        "Moon",
        "Nel",
        "River",
        "Robert",
        "Roger",
        "Sea",
        "Sewer",
        "Sun",
        "Simp",
        "Sull",
        "Thomp",
        "Town",
        "Up",
        "William",
    )

    val ROOT_EXPLICIT = ROOT + arrayOf(
        "Ass",
        "Balls",
        "Bastard",
        "Bitch",
        "Cum",
        "Cunt",
        "Damn",
        "Dick",
        "Fuck",
        "Penis",
        "Piss",
        "Seamen",
        "Shit",
        "Twat",
        "Wank",
    )

    val SUFFIX = arrayOf(
        "ander",
        "barf",
        "butt",
        "ell",
        "ens",
        "er",
        "ers",
        "es",
        "face",
        "ham",
        "haunter",
        "haver",
        "head",
        "in",
        "ington",
        "ins",
        "ivan",
        "junk",
        "ler",
        "long",
        "moon",
        "ons",
        "ovic",
        "ovitch",
        "s",
        "sby",
        "short",
        "son",
        "stone",
        "strong",
        "sun",
        "tall",
        "ter",
        "ton",
        "weak",
    )

    val SUFFIX_EXPLICIT = SUFFIX + arrayOf(
        "ass",
        "balls",
        "bastard",
        "bitch",
        "cum",
        "cunt",
        "dick",
        "fuck",
        "penis",
        "piss",
        "seamen",
        "shag",
        "shit",
        "twat",
        "wank",
    )

    val PREFIX = arrayOf(
        "O'",
        "Mc",
        "Mac",
        "Van",
        "Von",
    )
}