package com.thirdgallon.namegenerator.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material.Text
import androidx.compose.material.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import cafe.adriel.voyager.core.model.rememberScreenModel
import cafe.adriel.voyager.core.screen.Screen
import cafe.adriel.voyager.navigator.LocalNavigator
import com.thirdgallon.namegenerator.composables.BasicOptionsPanel
import com.thirdgallon.namegenerator.composables.ExpandableCard
import com.thirdgallon.namegenerator.composables.RoundedTextButton
import com.thirdgallon.namegenerator.database.SavedName
import com.thirdgallon.namegenerator.database.SavedNameDatabase
import com.thirdgallon.namegenerator.database.UUID
import com.thirdgallon.namegenerator.generator.NameGenerator
import com.thirdgallon.namegenerator.models.OptionsModel


object MainScreen : Screen {

    @Composable
    override fun Content() {
        val navigator = LocalNavigator.current
        val model = rememberScreenModel { OptionsModel() }
        var generated by remember { mutableStateOf(NameGenerator.shared.getLastGenerated()) }

        Column(
            Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            Text(
                text = generated,
                fontWeight = FontWeight.Bold,
                fontSize = 40.sp,
            )
            RoundedTextButton(
                text = "Generate Name",
                onClick = {generated = NameGenerator.shared.generate(model.getOptions()) }
            )
            ExpandableCard(text = "Generator Options") {
                BasicOptionsPanel(model)
            }

            RoundedTextButton(
                text = "Save Name",
                onClick = {
                    SavedNameDatabase.shared.writeName(
                        SavedName(
                            id = UUID().toString(),
                            name = NameGenerator.shared.getLastGenerated(),
                            description = "",
                        )
                    )
                }
            )
            TextButton(
                onClick = { navigator?.push(SavedScreen) },
                enabled = navigator != null,
                modifier = Modifier.padding(10.dp).fillMaxWidth(),
            ) {
                Text(
                    text = "View Saved",
                    fontSize = 24.sp,
                    modifier = Modifier.padding(vertical = 6.dp)
                )
            }
        }
    }
}