package com.thirdgallon.namegenerator.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material.Text
import androidx.compose.material.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import cafe.adriel.voyager.core.model.rememberScreenModel
import cafe.adriel.voyager.core.screen.Screen
import cafe.adriel.voyager.navigator.LocalNavigator
import com.thirdgallon.namegenerator.composables.BasicOptions
import com.thirdgallon.namegenerator.composables.ExpandableCard
import com.thirdgallon.namegenerator.composables.RoundedTextButton
import com.thirdgallon.namegenerator.composables.SaveConfirmDialog
import com.thirdgallon.namegenerator.database.SavedName
import com.thirdgallon.namegenerator.generator.NameGenerator
import com.thirdgallon.namegenerator.models.OptionsModel
import com.thirdgallon.namegenerator.models.SavedNamesModel


object MainScreen : Screen {

    @Composable
    override fun Content() {
        val navigator = LocalNavigator.current

        val model = rememberScreenModel { OptionsModel() }
        val savedNamesModel = rememberScreenModel { SavedNamesModel() }

        var generated by remember { mutableStateOf(NameGenerator.shared.getLastGenerated()) }
        val hasCurrentNameSaved = remember(generated, savedNamesModel.saved.value) {
            mutableStateOf(
                savedNamesModel.saved.value.contains(
                    SavedName("", generated, "")
                )
            )
        }
        val showSaveConfirmDialog = remember { mutableStateOf(false) }

        Column(
            Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            Text(
                text = generated,
                fontWeight = FontWeight.Bold,
                fontSize = 40.sp,
                textAlign = TextAlign.Center,
            )
            RoundedTextButton(
                text = "Generate Name",
                enabled = !(model.lockFirst.value && model.lockLast.value),
                onClick = {generated = NameGenerator.shared.generate(model.getOptions()) }
            )
            ExpandableCard(text = "Generator Options") {
                BasicOptions(model)
            }

            RoundedTextButton(
                text = "Save Name",
                enabled = generated.isNotEmpty() && !hasCurrentNameSaved.value,
                onClick = { showSaveConfirmDialog.value = true }
            )
            TextButton(
                onClick = { navigator?.push(SavedScreen) },
                enabled = navigator != null,
                modifier = Modifier.padding(10.dp).fillMaxWidth(),
            ) {
                Text(
                    text = "View Saved",
                    fontSize = 24.sp,
                    modifier = Modifier.padding(vertical = 6.dp)
                )
            }
        }

        SaveConfirmDialog(
            showSaveConfirmDialog,
            name = generated,
            onDismiss = { showSaveConfirmDialog.value = false },
            onSave = { description ->
                savedNamesModel.saveName(
                    name = NameGenerator.shared.getLastGenerated(),
                    description
                )
            }
        )
    }
}